export enum NON_LOCALIZED_STRING {
  appName = 'Session',
  appNamePossessive = "Session's",
  appNamePro = 'Session Pro',
  appNameProtocolV2 = 'Session Protocol v2',
  wordBeta = 'Beta',
  wordPro = 'Pro',
  wordsProBeta = 'Pro Beta',
  appToken = 'Session Token',
  foundationName = 'Session Technology Foundation',
  foundationNameWithAcronym = 'Session Technology Foundation (STF)',
  foundationAcronym = 'STF',
  foundationAcronymPossessive = "STF's",
  swissSupervisory = 'Federal Supervisory Authority for Foundations (ESA)',
  lokinet = 'Lokinet',
  ethNetworkName = 'Ethereum',
  arbNetworkName = 'Arbitrum',
  baseNetworkName = 'Base',
  ethSymbol = 'ETH',
  usdcSymbol = 'USDC',
  usdtSymbol = 'USDT',
  btcSymbol = 'BTC',
  bchSymbol = 'BCH',
  donationProviderName = 'Donorbox',
  donateAppealName = 'Cofounder of Session - Chris McCabe',
  donateSignerName = 'Chris McCabe',
  wordDesktop = 'Desktop',
  platformAndroid = 'Android',
  platformIos = 'iOS',
  platformStoreGoogle = 'Google Play Store',
  platformStoreGoogleShort = 'Google Play',
  wordFDroid = 'F-Droid',
  wordAPK = 'APK',
  wordIPAs = 'IPAs',
  platformStoreApple = 'Apple App Store',
  platformStoreAppleShort = 'App Store',
  standardUserFileUploadLimit = '10MB',
  standardUserMaxGroupSize = '100',
  proUserMaxGroupSize = '300',
  appNameRouterPossessive = "Session Router's",
  addressBitcoin = 'bc1qmuyaayx6xdfpvgdu5a0eqgzqrvr5d35f5y6k8w',
  addressBitcoinCash = 'qq7x2x7wa5gtl8s2wzq45h83vcczeenpgu2e2jlm4v',
  addressEthereum = '0xec793F400B2c133299ed78f22f5708872555F958',
  wordEthereumAddress = 'Ethereum Address',
  wordBitcoinAddress = 'Bitcoin Address',
  wordBitcoinCashAddress = 'Bitcoin Cash Address',
  wordErc20 = 'ERC-20',
  wordTokens = 'tokens',
  wordEvmCompatible = 'EVM-compatible',
  largeDonationAmount = '$50,000 dollars',
  wordCrowdin = 'Crowdin',
  wordSilentDonor = 'Silent Donor',
  effName = 'Electronic Frontier Foundation',
  wordApple = 'Apple',
  wordGoogle = 'Google',
}

export const SILENT_DONOR_LEGAL_DISCLAIMER =
  'Silent Donor is a third party service, and their terms and privacy policies govern your use of their services. The availability of tax deductible gift status may vary depending on your jurisdiction. The Session Technology Foundation does not accept any liability for any third party websites, apps, content, or other products or services.';

export const appUserNumber = 1_500_000;

export const localeArgs = { ...NON_LOCALIZED_STRING };
